#!/usr/bin/env bash
# LangSight quickstart — generates .env and starts the full stack.
# Usage: ./scripts/quickstart.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

echo "──────────────────────────────────────────────────────"
echo "  LangSight Quickstart"
echo "──────────────────────────────────────────────────────"
echo ""

# ── Check Docker is running ─────────────────────────────────────────────────
if ! docker info > /dev/null 2>&1; then
  echo "[error] Docker is not running. Start Docker Desktop and try again."
  exit 1
fi

# ── Generate .env if it doesn't exist ───────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  echo "[ok] .env already exists — skipping generation."
else
  echo "[..] Generating .env with secure random secrets..."

  API_KEY="ls_$(openssl rand -hex 32)"
  AUTH_SECRET="$(openssl rand -base64 32)"
  POSTGRES_PASSWORD="$(openssl rand -hex 16)"
  CLICKHOUSE_PASSWORD="$(openssl rand -hex 16)"
  ADMIN_PASSWORD="ls-$(openssl rand -hex 10)"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/quickstart.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not commit this file to git.

# API authentication
LANGSIGHT_API_KEYS=${API_KEY}

# Dashboard session secret
AUTH_SECRET=${AUTH_SECRET}

# Dashboard admin login
LANGSIGHT_ADMIN_EMAIL=admin@langsight.dev
LANGSIGHT_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Database passwords
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CLICKHOUSE_USER=langsight
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
EOF

  echo "[ok] .env created."
  echo ""
  echo "  Admin email:    admin@langsight.dev"
  echo "  Admin password: ${ADMIN_PASSWORD}"
  echo "  API key:        ${API_KEY}"
  echo ""
fi

# ── Create default config file if missing ────────────────────────────────────
CONFIG_FILE="$ROOT_DIR/.langsight.yaml"
# A previous failed run may have left a directory here (Docker creates one
# when the file is absent from the host). Remove it so we can write the file.
if [ -d "$CONFIG_FILE" ]; then
  rm -rf "$CONFIG_FILE"
fi
if [ ! -f "$CONFIG_FILE" ]; then
  echo "servers: []" > "$CONFIG_FILE"
  echo "[ok] .langsight.yaml created."
fi

# ── Build images ─────────────────────────────────────────────────────────────
echo "[..] Building images (first run takes 3-5 min — downloading dependencies)..."
cd "$ROOT_DIR"
docker compose build

# ── Start services ────────────────────────────────────────────────────────────
echo ""
echo "[..] Starting services..."
docker compose up -d

# ── Wait for healthy ──────────────────────────────────────────────────────────
echo "[..] Waiting for all services to be healthy..."
SECONDS=0
TIMEOUT=120
while true; do
  # Count healthy containers
  TOTAL=$(docker compose ps --services | wc -l | tr -d ' ')
  HEALTHY=$(docker compose ps | grep -c "healthy" || true)

  if [ "$HEALTHY" -ge "$TOTAL" ]; then
    break
  fi

  # Check for any failed/exited containers
  if docker compose ps | grep -qE "Exit|Error|unhealthy"; then
    echo ""
    echo "[error] A service failed to start. Logs:"
    echo ""
    # Show logs for the failed service
    for svc in api postgres clickhouse dashboard; do
      STATUS=$(docker compose ps "$svc" 2>/dev/null | tail -1 || true)
      if echo "$STATUS" | grep -qE "Exit|Error|unhealthy"; then
        echo "── $svc logs ──────────────────────────"
        docker compose logs --tail=20 "$svc"
        echo ""
      fi
    done
    echo "For full logs: docker compose logs"
    echo "To retry:      docker compose down -v && ./scripts/quickstart.sh"
    exit 1
  fi

  if [ "$SECONDS" -ge "$TIMEOUT" ]; then
    echo ""
    echo "[error] Timed out after ${TIMEOUT}s. Current status:"
    docker compose ps
    echo ""
    echo "For full logs: docker compose logs"
    exit 1
  fi

  printf "."
  sleep 3
done

echo ""
echo ""
echo "──────────────────────────────────────────────────────"
echo "  LangSight is running!"
echo "──────────────────────────────────────────────────────"
echo ""
echo "  Dashboard:  http://localhost:3003"
echo "  API:        http://localhost:8000"
echo ""
echo "  Login credentials:"
echo "    Email:    $(grep LANGSIGHT_ADMIN_EMAIL "$ENV_FILE" | cut -d= -f2)"
echo "    Password: $(grep LANGSIGHT_ADMIN_PASSWORD "$ENV_FILE" | cut -d= -f2)"
echo ""
echo "  API Key:    $(grep LANGSIGHT_API_KEYS "$ENV_FILE" | cut -d= -f2)"
echo ""
echo "  Containers running:"
docker compose ps --format "table {{.Service}}\t{{.Status}}" | tail -n +2 | sed 's/^/    /'
echo ""
echo "  Next steps:"
echo "    1. Open http://localhost:3003 and log in"
echo "    2. Instrument your agent:"
echo ""
echo "       import langsight"
echo "       langsight.auto_patch()"
echo ""
echo "       export LANGSIGHT_URL=http://localhost:8000"
echo "       export LANGSIGHT_API_KEY=<your-api-key>"
echo ""
echo "  Full guide: https://docs.langsight.dev/quickstart"
echo ""
echo "──────────────────────────────────────────────────────"
