"""
Adversarial tests for MCPClientProxy.session_id property and wrap() isolation.

Security invariants:
- Two wrap() calls with no session_id argument produce proxies with different
  session IDs — no shared __default__ state from the old pre-v0.3.2 design
- A session_id passed explicitly is forwarded unchanged into the proxy
- session_id is never None after wrap() with no args
- A sub-agent forwarding the orchestrator's session_id receives the exact same
  string — no mutation, truncation, or prefix injection

These tests exist because the original bug was exactly this: all no-session-id
proxies shared a single "__default__" loop-detector entry, meaning proxy A
could push proxy B into a loop-blocked state. The fix is _new_session_id() on
every wrap() call when no session_id is supplied.
"""

from __future__ import annotations

import re
from unittest.mock import MagicMock

import pytest

from langsight.sdk.client import LangSightClient, MCPClientProxy

pytestmark = pytest.mark.security

_HEX_RE = re.compile(r"^[0-9a-f]{32}$")


def _client() -> LangSightClient:
    return LangSightClient(url="http://localhost:8000")


def _mcp() -> MagicMock:
    return MagicMock()


class TestAutoGeneratedSessionIdIsolation:
    """Two wrap() calls with no session_id must produce independent, non-null IDs.

    Regression guard for the pre-v0.3.2 bug where both proxies mapped to
    '__default__' and shared loop-detector / budget state cross-session.
    """

    def test_two_wraps_no_args_produce_different_session_ids(self) -> None:
        """Core regression: no shared __default__ state between independent proxies."""
        client = _client()
        proxy_a = client.wrap(_mcp(), server_name="srv-a")
        proxy_b = client.wrap(_mcp(), server_name="srv-b")
        assert proxy_a.session_id != proxy_b.session_id, (
            "Both proxies share the same session_id — "
            "wrap() is not generating a unique ID per call"
        )

    def test_wrap_no_args_session_id_is_not_none(self) -> None:
        """wrap() with no session_id must auto-generate one, never return None."""
        client = _client()
        proxy = client.wrap(_mcp())
        assert proxy.session_id is not None

    def test_wrap_no_args_session_id_is_not_empty_string(self) -> None:
        client = _client()
        proxy = client.wrap(_mcp())
        assert proxy.session_id != ""

    def test_wrap_no_args_session_id_is_valid_hex(self) -> None:
        """Auto-generated ID must match the uuid4().hex format (32 lowercase hex chars)."""
        client = _client()
        proxy = client.wrap(_mcp())
        assert _HEX_RE.match(proxy.session_id), (
            f"Auto-generated session_id {proxy.session_id!r} is not 32-char lowercase hex"
        )

    def test_ten_wraps_all_unique_session_ids(self) -> None:
        """10 independent wrap() calls must produce 10 distinct IDs."""
        client = _client()
        ids = [client.wrap(_mcp()).session_id for _ in range(10)]
        assert len(set(ids)) == 10, (
            f"Collision in 10 auto-generated session IDs: {ids}"
        )

    def test_wrap_no_args_session_id_has_no_default_sentinel(self) -> None:
        """The literal string '__default__' must never surface as a session_id.

        That sentinel was an internal implementation detail that leaked in the
        old design. It must not be visible through the public .session_id property.
        """
        client = _client()
        for _ in range(20):
            proxy = client.wrap(_mcp())
            assert proxy.session_id != "__default__", (
                "wrap() is returning the internal '__default__' sentinel as session_id"
            )


class TestExplicitSessionIdForwarding:
    """An explicitly supplied session_id must be forwarded unchanged into the proxy.

    This covers the sub-agent pattern: the orchestrator reads proxy.session_id
    and passes it verbatim to wrap() for the sub-agent. Any mutation here would
    sever the trace linkage in the dashboard.
    """

    def test_explicit_session_id_is_preserved(self) -> None:
        client = _client()
        explicit = "cafebabe0123456789abcdef01234567"
        proxy = client.wrap(_mcp(), session_id=explicit)
        assert proxy.session_id == explicit

    def test_explicit_session_id_not_mutated(self) -> None:
        """The SDK must not prefix, suffix, or truncate the caller-supplied ID."""
        client = _client()
        original = "deadbeef" * 4  # 32-char hex
        proxy = client.wrap(_mcp(), session_id=original)
        assert proxy.session_id == original
        assert len(proxy.session_id) == len(original)

    def test_sub_agent_receives_exact_orchestrator_session_id(self) -> None:
        """Simulate the multi-agent handoff pattern from the API docs.

        orchestrator_proxy.session_id → passed to sub_proxy via wrap() →
        sub_proxy.session_id must equal orchestrator_proxy.session_id.
        """
        client = _client()
        orchestrator_proxy = client.wrap(_mcp(), server_name="jira-mcp", agent_name="orch")
        orchestrator_session_id = orchestrator_proxy.session_id

        sub_proxy = client.wrap(
            _mcp(),
            server_name="crm-mcp",
            agent_name="billing",
            session_id=orchestrator_session_id,
        )
        assert sub_proxy.session_id == orchestrator_session_id, (
            "Sub-agent proxy session_id does not match the orchestrator's session_id"
        )

    def test_empty_string_session_id_is_auto_replaced(self) -> None:
        """Passing an empty string is treated the same as None — auto-generates.

        Regression: empty string bypassed the None check and was forwarded as "",
        which is not a valid session ID and collides with nothing but also leaks
        through as a useless key in loop-detector / budget dicts.
        Fix: wrap() uses `session_id if session_id else _new_session_id()`.
        """
        client = _client()
        proxy = client.wrap(_mcp(), session_id="")
        assert proxy.session_id != "", "Empty string must be replaced with a generated ID"
        assert len(proxy.session_id) == 32, "Generated ID must be 32 hex chars"

    def test_session_id_property_returns_consistent_value(self) -> None:
        """Reading session_id twice must return the same string — not regenerate."""
        client = _client()
        proxy = client.wrap(_mcp())
        first = proxy.session_id
        second = proxy.session_id
        assert first == second, "session_id property is not stable across reads"


class TestSessionIdType:
    """session_id must always be a string, not an integer, UUID object, or bytes."""

    def test_auto_generated_session_id_is_str(self) -> None:
        client = _client()
        proxy = client.wrap(_mcp())
        assert isinstance(proxy.session_id, str)

    def test_explicit_session_id_is_returned_as_str(self) -> None:
        client = _client()
        proxy = client.wrap(_mcp(), session_id="abc123" + "0" * 26)
        assert isinstance(proxy.session_id, str)

    def test_proxy_is_mcp_client_proxy_instance(self) -> None:
        """wrap() must return an MCPClientProxy, not a bare MagicMock or other type."""
        client = _client()
        proxy = client.wrap(_mcp())
        assert isinstance(proxy, MCPClientProxy)
